### ISSUE TITLE
Cannot train due to assertion 

### ISSUE THREAD

**Issue by arjungrylls** [TensorBox/TensorBox#168]
Hello, 
i was able to successfully train to detect plant crops with this code a few days ago. Now when i tried to train with different plants , i get the following error as 

arjun@arjun-HP-Notebook:~/tensorbox$ python train.py --hypes hypes/overfeat_rezoom.json  --logdir output
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train.py", line 439, in thread_loop
    for d in gen:
  File "/home/arjun/tensorbox/utils/train_utils.py", line 82, in load_data_gen
    for d in data:
  File "/home/arjun/tensorbox/utils/train_utils.py", line 51, in load_idl_tf
    anno = rescale_boxes(I.shape, anno, H["image_height"], H["image_width"])
  File "/home/arjun/tensorbox/utils/train_utils.py", line 18, in rescale_boxes
    assert r.x1 < r.x2
AssertionError

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train.py", line 439, in thread_loop
    for d in gen:
  File "/home/arjun/tensorbox/utils/train_utils.py", line 82, in load_data_gen
    for d in data:
  File "/home/arjun/tensorbox/utils/train_utils.py", line 51, in load_idl_tf
    anno = rescale_boxes(I.shape, anno, H["image_height"], H["image_width"])
  File "/home/arjun/tensorbox/utils/train_utils.py", line 18, in rescale_boxes
    assert r.x1 < r.x2
AssertionError

Step: 0, lr: 0.001000, Train Loss: 0.75, Softmax Test Accuracy: 75.7%, Time/image (ms): 0.0

the training halts with this step for a very long time. 
Can anybody help me....????

**Comment by Russell91** [comment]
This is an indication that your bounding box annotation input contains some bugs. Perhaps you can run through your json file and programmatically look for any boxes that have the first x coordinate larger than the second?
