### ISSUE TITLE
KeyError: 'slim_basename'

### ISSUE THREAD

**Issue by CWallbridge** [TensorBox/TensorBox#185]
Attempting to run from the ReInspect Installation & Training instructions:

`python train.py --hypes hypes/lstm_rezoom.json --gpu 0 --logdir output`

I encounter the following error:

`
Traceback (most recent call last):
  File "train.py", line 542, in <module>
    main()
  File "train.py", line 539, in main
    train(H, test_images=[])
  File "train.py", line 444, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 337, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 238, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, phase, reuse)
  File "train.py", line 125, in build_forward
    cnn, early_feat = googlenet_load.model(x, H, reuse)
  File "/home/chris/ws/src/TensorBox/utils/googlenet_load.py", line 6, in model
    if H['slim_basename'] == 'resnet_v1_101':
KeyError: 'slim_basename'
`
Seems lstm_rezoom.json does not contain this key. The file lstm_resnet_rezoom.json does. Should the instructions be referring to this file instead? Is lstm_rezoom.json no longer used?

Ubuntu 16.04
Tensorflow 0.12.1

**Comment by Russell91** [comment]
Yeah, looks like those didn't get updated. You can copy those parameters from lstm_resnet_rezoom, or just use that one instead.
