### ISSUE TITLE
Assertion error r.x1 < r.x2

### ISSUE THREAD

**Issue by tladyman** [TensorBox/TensorBox#191]
Every time I run with my own data I get the error:

```
Traceback (most recent call last):
  File "evaluate.py", line 105, in <module>
    main()
  File "evaluate.py", line 86, in main
    pred_annolist, true_annolist = get_results(args, H)
  File "evaluate.py", line 56, in get_results
    pred_anno = rescale_boxes((H["image_height"], H["image_width"]), pred_anno, orig_img.shape[0], orig_img.shape[1])
  File "tensorbox/utils/train_utils.py", line 18, in rescale_boxes
    assert r.x1 < r.x2
AssertionError
```
Any ideas what it means? Fairly likely it's me doing something wrong. My images are resized to match the hypes.json file

**Comment by AdamWP** [comment]
What are the dimensions of your images?  I believe the dimensions need to be a multiple of 32.

**Comment by tladyman** [comment]
Hi thanks. They're 480x320 same as the default

**Comment by mkreich** [comment]
It means that your rectangles have width = 0 or x1 is somehow bigger then x2.
Use a debugger (ipdb) at line 18 e.g. with 
```
        import ipdb
        ipdb.set_trace()
```
and print the x1/x2 coordinates of the the anno.rects.

**Comment by jajoe** [comment]
Same issue with the example in the README. I use tensorflow 1.0 and I run the following command (copy/paste from the tuto) : 
python evaluate.py --weights output/overfeat_rezoom_2017_02_21_19.29/save.ckpt-201 --test_boxes data/brainwash/val_boxes.json

**Comment by Russell91** [comment]
That shouldn't be happening with the readme example. Can you reclone and
confirm? Also, please just say print r.x1, r.x2 right before the assert
statement and describe what happens. You can always remove the assert
statement as well. If anyone wants to submit a pull request describing the
semantics of what that assert statement means, that would be useful as well.

**Comment by jajoe** [comment]
Thanks for your answer Russell91. It was probably my fault, because after running once again the script download_data.sh it works.

**Comment by Suinga** [comment]
I also met this Assertion error when doing evaluate, was the regression forced to eliminate negative and zero width/height? Thank you.
