### ISSUE TITLE
hungarian.so: undefined symbol: _ZN10tensorflow[...]11Ev

### ISSUE THREAD

**Issue by LucasMahieu** [TensorBox/TensorBox#194]
I'm trying to use ReInspect, so when i use : 
python train.py --hypes hypes/lstm_resnet_rezoom.json --gpu 0 --logdir output

I get : 
tensorflow.python.framework.errors_impl.NotFoundError: utils/hungarian/hungarian.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

Do you have an idea ? 
thanks in advance

**Comment by jasrk11** [comment]
`cd /path/to/tensorbox/utils && make && cd ..` and then try training your model

**Comment by LucasMahieu** [comment]
Thanks for your reply.
but this is what i did.
look to the result here : 
''' make && make hungarian && cd .. ''' 
" 
pip install runcython
Requirement already satisfied: runcython in /home/lm249982/stage_lucas_2017/PythonEnv/tensorflow/lib/python2.7/site-packages
Requirement already satisfied: Cython>=0.10 in /home/lm249982/stage_lucas_2017/PythonEnv/tensorflow/lib/python2.7/site-packages (from runcython)
makecython++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp"
make: rien à faire pour « hungarian ». " 

and when I try to do  
''' python train.py --hypes hypes/lstm_resnet_rezoom.json --gpu 0 --logdir output ''' 
I get : 
WARNING:tensorflow:<tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.BasicLSTMCell object at 0x7fd5bacf0790>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Traceback (most recent call last):
  File "train.py", line 546, in <module>
    main()
  File "train.py", line 543, in main
    train(H, test_images=[])
  File "train.py", line 448, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 341, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 249, in build_forward_backward
    hungarian_module = tf.load_op_library('utils/hungarian/hungarian.so')
  File "/home/lm249982/stage_lucas_2017/PythonEnv/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: utils/hungarian/hungarian.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

An idea ?

**Comment by jasrk11** [comment]
#129

**Comment by jasrk11** [comment]
Looks like this issue has been asked before. Referencing them for you.
#129 #60

**Comment by LucasMahieu** [comment]
Thanks a lot for the solution.

**Comment by BolongXIONG** [comment]
i have the same problems as yours. i am using TensorFlow 0.11. I cannot solve the problem in the way refeffered in the #60  :( how can you solve this problem?

**Comment by willSapgreen** [comment]
When executing "make hungarian", I do have the similar issues.

First, I encounter "**/mutex.h:25:22: fatal error: nsync_cv.h: No such file or directory**"
The solution is
adding "-I $TF_INC/external/nsync/public" to utils/Makefile

Then I encounter "**undefined symbol: _ZTIN10tensorflow8OpKernelE**"
The solution is
adding "TF_LIB=$$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())') && \" after TF_INC
and -L$$TF_LIB -ltensorflow_framework to the compiler flags to utils/Makefile

Now my local utils/Makefile looks like
SHELL := /bin/bash

.PHONY: all
all:
	pip install runcython
	makecython++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp"

hungarian: hungarian/hungarian.so

hungarian/hungarian.so:
	cd hungarian && \
	TF_INC=$$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())') && \
	TF_LIB=$$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())') && \
	if [ `uname` == Darwin ];\
	then g++-5 -std=c++11 -shared hungarian.cc -o hungarian.so -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -I $$TF_INC/external/nsync/public -I $$TF_INC -L$$TF_LIB -ltensorflow_framework -undefined dynamic_lookup;\
	else g++-5 -std=c++11 -shared hungarian.cc -o hungarian.so -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -I $$TF_INC/external/nsync/public -I $$TF_INC -L$$TF_LIB -ltensorflow_framework; fi

And now I can run lstm.json

Hopefully, it is helpful.

**Comment by PumayHui** [comment]
@willSapgreen 
I did as your instructions, but look to the result here :
`
Traceback (most recent call last):
  File "train.py", line 566, in <module>
    main()
  File "train.py", line 563, in main
    train(H, test_images=[])
  File "train.py", line 457, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 363, in build
    grads, norm = tf.clip_by_global_norm(tf.gradients(loss['train'], tvars), H['clip_norm'])
  File "/home/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 588, in gradients
    _VerifyGeneratedGradients(in_grads, op)
  File "/hom/anaconda2/envs/py3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py", line 278, in _VerifyGeneratedGradients
    "inputs %d" % (len(grads), op.node_def, len(op.inputs)))
ValueError: Num gradients 1 generated for op name: "decoder_1/Hungarian"
op: "Hungarian"
input: "decoder/concat"
input: "decoder_1/Reshape"
input: "decoder_1/Cast"
input: "decoder_1/Hungarian/overlap_threshold"
 do not match num inputs 4
`

:( how can you solve this problem?
