### ISSUE TITLE
Shape mismatch issue related to rnn_len

### ISSUE THREAD

**Issue by totoroTree** [TensorBox/TensorBox#195]
When I try to train using LTSM, it seems that the shape of feature map does not match with expected shapes, does anyone meet the same issue?

Error message:
**Traceback (most recent call last):
  File "train.py", line 626, in <module>
    main()
  File "train.py", line 623, in main
    train(H, test_images=[])
  File "train.py", line 520, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 405, in build
    boxes_loss[phase], class_loss[phase], pred_class) = build_forward_backward(H, x, phase, boxes, flags, multi_class_flags)
  File "train.py", line 267, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, phase, reuse)
  File "train.py", line 207, in build_forward
    pred_class_squash = tf.reshape(pred_class, [outer_size * H['rnn_len'], H['num_classes']])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2630, in reshape
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2329, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1717, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1667, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Cannot reshape a tensor with 600 elements to shape [1500,2] (3000 elements) for 'decoder/Reshape_18' (op: 'Reshape') with input shapes: [300,1,2], [2].**

Hypes files:

> {
    "data": {
        "train_idl": "./train_data.json",
        "test_idl": "./test_data.json",
        "truncate_data": false,
        "labels": ["Stop", "StopL", "Go", "GoF", "GoL", "Warn", "WarnL"]
    },
    "logging": {
        "display_iter": 50,
        "save_iter": 5000,
        "tfdebug": true
    },
    "solver": {
        "opt": "RMS",
        "use_jitter": true,
        "rnd_seed": 1,
        "epsilon": 0.00001, 
        "learning_rate": 0.001, 
        "learning_rate_step": 33000, 
        "hungarian_iou": 0.25,
        "weights": "",
        "head_weights": [1.0, 0.1]
    },
    "use_lstm": true,
    "use_rezoom": true,
    "biggest_box_px": 10000,
    "rezoom_change_loss": "center",
    "rezoom_w_coords": [-0.25, 0.25],
    "rezoom_h_coords": [-0.25, 0.25],
    "reregress": true,
    "focus_size": 1.8,
    "early_feat_channels": 256,
    "later_feat_channels": 832,
    "avg_pool_size": 5,
    "num_lstm_layers": 2,
    "image_width": 640, 
    "image_height": 480,
    "grid_height": 15, 
    "grid_width": 20,
    "batch_size": 1, 
    "region_size": 32,
    "clip_norm": 1.0,
    "lstm_size": 500,
    "deconv": false,
    "num_classes": 2,
    "rnn_len": 5
}

**Comment by jongsony** [comment]
You have 7 lablels: "Stop", "StopL", "Go", "GoF", "GoL", "Warn", "WarnL". 
I assumed you have 7 classes. Right? 
then I think you should match "num_classes": 2 to your caterories. Why don't you change "num_classes": 8 from 2. Here 8 = number of your caterories (7) + background (1)
