### ISSUE TITLE
error using tensorflow 1.0.0

### ISSUE THREAD

**Issue by kirk86** [TensorBox/TensorBox#201]
Hi guys I'm receiving the following errors using tensorflow version 1.0.0 from conda.

```
python train.py --hypes hypes/overfeat.json --logdir output
Traceback (most recent call last):
  File "train.py", line 546, in <module>
    main()
  File "train.py", line 543, in main
    train(H, test_images=[])
  File "train.py", line 448, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 341, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 244, in build_forward_backward
    pred_boxes, pred_logits, pred_confidences = build_forward(H, x, phase, reuse)
  File "train.py", line 129, in build_forward
    cnn, early_feat = googlenet_load.model(x, H, reuse)
  File "/home/user/projects/TensorBox/utils/googlenet_load.py", line 6, in model
    if H['slim_basename'] == 'resnet_v1_101':
KeyError: 'slim_basename'
```

**Comment by robrao** [comment]
Those errors are not related to the Tensorflow version. The json hype files for the inception encoder have not been update to work with the latest changes to the repo. You can use the resnet hype files, or overfeat_rezoom.json, or you can take a look at this PR #196

**Comment by kirk86** [comment]
@robrao thanks a lot for the clarification. I've tested your suggestion and it seems that on my system only `overfeat_rezoom` is working.

for `overfeat_resnet` I get the following errors:
```
W tensorflow/core/kernels/queue_base.cc:294] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "train.py", line 546, in <module>
    main()
  File "train.py", line 543, in main
    train(H, test_images=[])
  File "train.py", line 482, in train
    init_fn(sess)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 586, in callback
    saver.restore(session, model_path)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/user/TensorBox/data/resnet_v1_101.ckpt
	 [[Node: save_1/RestoreV2_19 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_19/tensor_names, save_1/RestoreV2_19/shape_and_slices)]]

Caused by op u'save_1/RestoreV2_19', defined at:
  File "train.py", line 546, in <module>
    main()
  File "train.py", line 543, in main
    train(H, test_images=[])
  File "train.py", line 478, in train
    [x for x in tf.global_variables() if x.name.startswith(H['slim_basename']) and H['solver']['opt'] not in x.name])
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 584, in assign_from_checkpoint_fn
    saver = tf_saver.Saver(var_list, reshape=reshape_variables)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/user/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/user/TensorBox/data/resnet_v1_101.ckpt
	 [[Node: save_1/RestoreV2_19 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_19/tensor_names, save_1/RestoreV2_19/shape_and_slices)]]
```

for `lstm_rezoom` I get the following errors:

```
Traceback (most recent call last):
  File "train.py", line 546, in <module>
    main()
  File "train.py", line 543, in main
    train(H, test_images=[])
  File "train.py", line 448, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 341, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 242, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, phase, reuse)
  File "train.py", line 129, in build_forward
    cnn, early_feat = googlenet_load.model(x, H, reuse)
  File "/home/projects/TensorBox/utils/googlenet_load.py", line 6, in model
    if H['slim_basename'] == 'resnet_v1_101':
KeyError: 'slim_basename'
```

for `lstm_resnet_rezoom` I get the following errors:

```
WARNING:tensorflow:<tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.BasicLSTMCell object at 0x7f2198a5f110>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Traceback (most recent call last):
  File "train.py", line 546, in <module>
    main()
  File "train.py", line 543, in main
    train(H, test_images=[])
  File "train.py", line 448, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 341, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 249, in build_forward_backward
    hungarian_module = tf.load_op_library('utils/hungarian/hungarian.so')
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: utils/hungarian/hungarian.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
```

Finally, could you please indicate what is the appropriate/correct way to use my own dataset. Do I need to transform it to idl files?

Thanks in advance and apologies for the numerous number of questions.
