### ISSUE TITLE
Running on Windows 10 / Tensorflow 1.0.1

### ISSUE THREAD

**Issue by cheind** [TensorBox/TensorBox#205]
Hi there,

although probably not intended by the author, I'm trying to run this on Windows 10 x64 / Python 3.5  with Tensorflow 1.0.1 with GPU support. I've already made some progress such as
 - Converting Python 2.7 constructs to Python 3.x (mostly `xrange -> range`, `gen.next() -> next(gen)`, `print "" -> print("")`),
 - Fixing import statements
 - Compiling `stitch_wrapper` as .pyd extension using CMake / Visual Studio 2015.

I would happily share my experience in a structured way once I get it running. I'm currently stuck with an error from Tensorflow stemming probably from [`py_func.cc`](https://github.com/tensorflow/tensorflow/blob/77c8a03c3b398a95cd01ef3a1c7f5bed4935432b/tensorflow/python/lib/core/py_func.cc#L248)

`UnimplementedError (see above for traceback): Unsupported object type AnnoRect`

Following additional info is given

```
Unsupported object type AnnoRect
         [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1_DequeueMany, strided_slice_12/_497, strided_slice_13/_499, Variable/read, PyFunc_1/input_4)]]
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\kernels\queue_base.cc:294] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\kernels\queue_base.cc:294] _1_fifo_queue_1: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "C:\Users\cheind\AppData\Local\Continuum\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
    return fn(*args)
  File "C:\Users\cheind\AppData\Local\Continuum\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
    status, run_metadata)
  File "C:\Users\cheind\AppData\Local\Continuum\Anaconda3\envs\py35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\cheind\AppData\Local\Continuum\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.UnimplementedError: Unsupported object type AnnoRect
         [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1_DequeueMany, strided_slice_12/_497, strided_slice_13/_499, Variable/read, PyFunc_1/input_4)]]
```

Any help would be greatly appreciated.

**Comment by RomanSteinberg** [comment]
@cheind Have you build tensorbox for python 3.5? I mean `make` and other install commands.

**Comment by cheind** [comment]
@RomanSteinberg i replaced make by a CMake script that builds the necessary stitch_wrapper using Visual Studio 2015. Only thing I had to change in the code was memory allocation in the hungarian method. But I don't think that the issue I currently observe `UnimplementedError (see above for traceback): Unsupported object type AnnoRect`. 

Interestingly enough I was able to run the evaluation (`evaluation.py`) without much issues (except for path changes). So I assume this is somehow related to training.

**Comment by cheind** [comment]
@RomanSteinberg ok, got it running. Issue was that AnnoRect is returned from a function wrapped by `tf.py_func`. According to this test custom datatypes are not support in return values. However, it seems like that this behavior of `tf.py_func` was not introduced in 1.0 but was already present in 0.11. The relevant code that caused the issue is in `train.py` where you enqueue two logging related tasks. So far I have commented the lines and now it seems to train and evaluate fine on Windows 10 / Python 3.5 / Tensorflow 1.0 x64.

I will have a look into the logging functionality tomorrow, since currently tensorboard is not showing anything useful on the progress. Next step would be to make this available to more people.

Do you intend to update the code? If not, I can submit PRs for Python 3.5 / Tensorflow 1.0 and separately   additions for Windows building of extension. Would you be willing to have a look at those and merge them?

**Comment by cheind** [comment]
@RomanSteinberg forked your repo here

https://github.com/cheind/TensorBox/tree/develop

In case you want to review some of the changes.

The code is functional on Windows 10 / Python 3.5 / Tensorflow 1.0. It will be polished as I advance.

**Comment by RomanSteinberg** [comment]
@cheind I niether have rights to merge nor using TF on Win. So, I'm not really interested in this code. But I'm sure you did a good step, because I can see a lot of issues related Windows.

**Comment by cheind** [comment]
@RomanSteinberg thanks, got the names mixed up, sorry. So, @Russell91 not sure if you followed this thread here, but I'm having your code running nicely on Windows 10 / Python 3.5 / Tensorflow 1.0 at

https://github.com/cheind/TensorBox/tree/develop

I will be updating the usage for Windows users on Monday. I thought that it might be valueable for others Windows users, so we could either consider a PR or maybe some kind of perm-link for those searching a Windows solution.

**Comment by AndreaFar** [comment]
@cheind I get this error with your fork `undefined symbol: _Py_ZeroStruct`

**Comment by cheind** [comment]
@AndreaFar interesting, I didn't have a look at how backward compatible my changes are. However, this looks rather not related to my changes. Did you try it with the orignal master? I will enable travis for my fork soon.

**Comment by AndreaFar** [comment]
@cheind The original seems not working for different problems. I suggest to add the list of dependency and OS  currently tested and working correctly. This project depends on a lot of different modules and is very difficult understand what is going wrong if everyone try to test use different version of some lib that can cause issue with some function.

**Comment by AndreaFar** [comment]
@cheind  I have seen in your fork that you have been able to compile stitch_wrapper on windows. Could you tell me exactly what is the correct procedure to compile  stitch_wrapper on Windows?

**Comment by Aminullah6264** [comment]
Dear @cheind 
I have used your code on windows 10 that really work for me
Know i have saved my model, and i want us it for tensorflowsharp C#
can i use this stitch_wrapper to get ROIs in C#

**Comment by AndreaFar** [comment]
@Aminullah6264 How you have compiled stitch_wrapper on Windows?

**Comment by Aminullah6264** [comment]
Dear @AndreaFar i didn't, but @cheind did it for windows.
Download clone from given link

https://github.com/cheind/TensorBox/tree/develop

**Comment by Aminullah6264** [comment]
@AndreaFar  i need to run these for C# is it possible
i have trained my model and can run C# but i have prolem in last step which this stitch_wrapers 

and add rectangle code

**Comment by cheind** [comment]
@AndreaFar compiling the stitch_wrapper on Windows uses CMake. See 

https://github.com/cheind/TensorBox/blob/develop/utils/CMakeLists.txt

It  first invokes cython, then compiles a static dynamic library and copies it as `.pyd` to the final directory.

**Comment by Aminullah6264** [comment]
@cheind  why not answer me??
is it not possible??

**Comment by cheind** [comment]
Sorry @Aminullah6264 didn't recognize that you have issues with compiling...I haven't used C# in a long time, so I'm not confident that I can answer your question adequately. Calling C-functions from C# can be done using [platform invoke ](https://msdn.microsoft.com/en-us/library/aa288468(v=vs.71).aspx). You might find your answer there.

**Comment by Aminullah6264** [comment]
@cheind  Thanks i will try.
