### ISSUE TITLE
"Failed to find any matching files for /shared/TensorBox-1.0/data/inception_v1.ckpt" on running train.py

### ISSUE THREAD

**Issue by javadba** [TensorBox/TensorBox#243]
When  running 'python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output' there are  many warnings like:

W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /shared/TensorBox-1.0/data/inception_v1.ckpt
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /shared/TensorBox-1.0/data/inception_v1.ckpt
W

Finally the command fails:

W tensorflow/core/kernels/queue_base.cc:294] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:294] _1_fifo_queue_1: Skipping cancelled enqueue attempt with queue not closed

Traceback (most recent call last):
  File "train.py", line 549, in <module>
    main()
  File "train.py", line 546, in main
    train(H, test_images=[])
  File "train.py", line 482, in train
    init_fn(sess)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 586, in callback
    saver.restore(session, model_path)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /shared/TensorBox-1.0/data/inception_v1.ckpt
	 [[Node: save_1/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_2/tensor_names, save_1/RestoreV2_2/shape_and_slices)]]

Caused by op u'save_1/RestoreV2_2', defined at:
  File "train.py", line 549, in <module>
    main()
  File "train.py", line 546, in main
    train(H, test_images=[])
  File "train.py", line 478, in train
    [x for x in tf.global_variables() if x.name.startswith(H['slim_basename']) and H['solver']['opt'] not in x.name])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 584, in assign_from_checkpoint_fn
    saver = tf_saver.Saver(var_list, reshape=reshape_variables)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /shared/TensorBox-1.0/data/inception_v1.ckpt
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /shared/TensorBox-1.0/data/inception_v1.ckpt
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /shared/TensorBox-1.0/data/inception_v1.ckpt
	 [[Node: save_1/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_2/tensor_names, save_1/RestoreV2_2/shape_and_slices)]]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train.py", line 445, in thread_loop
    sess.run(enqueue_op[phase], feed_dict=make_feed(d))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_1_enqueue = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1, _recv_Placeholder_0, _recv_Placeholder_1_0, _recv_Placeholder_2_0)]]

Caused by op u'fifo_queue_1_enqueue', defined at:
  File "train.py", line 549, in <module>
    main()
  File "train.py", line 546, in main
    train(H, test_images=[])
  File "train.py", line 437, in train
    enqueue_op[phase] = q[phase].enqueue((x_in, confs_in, boxes_in))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 322, in enqueue
    self._queue_ref, vals, name=scope)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1569, in _queue_enqueue_v2
    name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

I have tried both HEAD of master (5/21/17) and from the downloaded source of  'TensorBox-1.0'.  Platform is El Capitan.

**Comment by safijari** [comment]
This is the same as #236. It's looking for pre-trained weights for a google convnet.

**Comment by javadba** [comment]
I was simply following the build instructions in the README.md .. so do
they need to be updated?  How to be able to run the command listed there
"python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output
"

2017-05-22 12:00 GMT-07:00 Jariullah Safi <notifications@github.com>:

**Comment by safijari** [comment]
So, there's the data download script. This gets a bunch of tensorflow checkpoint files as a starting point. Two of those files are downloaded from the maintainer's personal website but both the maintainer and the website appear to have gone dark. If you go here (https://app.box.com/s/pqkum8dq3849chjz4pp9ctjpykrz8s15) and put those files in a folder titled `data` (in the same directory that holds the folder called `hypes`), things should work for you.

I suppose the readme should be updated, I'm hoping the maintainer comes back.
